# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: PR

on:
  workflow_dispatch:

  pull_request:
    paths-ignore:
      - '**.md'
      - 'platforms.yml'
      - '.linkcheck-ignore.yml'

jobs:
  pr-checks:
    name: Checks
    uses: seL4/ci-actions/.github/workflows/pr.yml@master

  clippy_check:
    runs-on: [self-hosted, macos, ARM64]
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        # Make sure CI fails on all warnings, including Clippy lints
        run: nix develop --ignore-environment -c bash -c "cd tool/microkit && cargo-clippy --all-targets --all-features -- -D warnings -Wclippy::get_unwrap"

  rustfmt_check:
    runs-on: [self-hosted, macos, ARM64]
    steps:
      - uses: actions/checkout@v4
      - name: Run rustfmt
        run: nix develop --ignore-environment -c bash -c "cd tool/microkit && cargo-fmt --check"

  code:
    name: Freeze Code
    runs-on: ubuntu-latest
    outputs:
      xml: ${{ steps.repo.outputs.xml }}
    steps:
      - id: repo
        uses: seL4/ci-actions/repo-checkout@master
        with:
          manifest_repo: seL4/microkit-manifest
          manifest_branch: main
          manifest: main.xml
          # Needed because otherwise github makes this a local-only merge commit
          sha: ${{ github.event.pull_request.head.sha }}

  sdk-build:
    needs: code
    name: Build SDK
    uses: ./.github/workflows/_sdk.yaml
    with:
      xml: ${{ needs.code.outputs.xml }}
